services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: dbpaquera
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  # Definindo o volume postgres_data	  