spring:
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/dbpaquera
    driver-class-name: org.postgresql.Driver  # Driver JDBC do PostgreSQL
            
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Dialeto SQL do PostgreSQL
        format_sql: true
        hbm2ddl:
          auto: update  # Pode ser 'create', 'create-drop' ou 'update'

server:
  error:
    include-stacktrace: never

logging:
  level:
    root: info 
    org:
      springframework:
        web: ERROR