spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbpaquera
    username: admin
    password: j@mEm1c
    driver-class-name: org.postgresql.Driver  # Driver JDBC do PostgreSQL
    
  security:
    oauth2:
      client:
        registration:   
          google:   
            client-id: 216537186912-5nip7levqof03hcajdv5901hv5gqufl0.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: autorization_code
            client-authentication-method: client_seccret_post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.goog.eapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Dialeto SQL do PostgreSQL
        format_sql: true
        hbm2ddl:
          auto: update  # Pode ser 'create', 'create-drop' ou 'update'

server:
  error:
    include-stacktrace: never

logging:
  level:
    root: info 
    org:
      springframework:
        web: ERROR